import * as SETUP_BAHASA from './SETUP_BAHASA';
import * as SETUP_ETNIS from './SETUP_ETNIS';
import * as SETUP_JOB_TYPE from './SETUP_JOB_TYPE';
import * as SETUP_KEBANGSAAN from './SETUP_KEBANGSAAN';
import * as SETUP_EDUCATION from './SETUP_EDUCATION';
import * as SETUP_SMF_DOKTER from './SETUP_SMF';
import * as SETUP_SPESIALISASI_DOKTER from './SETUP_SPESIALISASI_DOKTER';
import * as SETUP_STATUS_DOKTER from './SETUP_STATUS_DOKTER';
import * as JENIS_IDENTITAS from './JENIS_IDENTITAS';
import * as MARITAL_STATUS from './MARITAL_STATUS';
import * as SETUP_PROVINSI from './SETUP_PROVINSI';
import * as SETUP_KOTA from './SETUP_KOTA';
import * as SETUP_KECAMATAN from './SETUP_KECAMATAN';

export const API = Object.assign({}, {
    "SETUP_BAHASA": SETUP_BAHASA,
    "SETUP_ETNIS": SETUP_ETNIS,
    "SETUP_JOB_TYPE": SETUP_JOB_TYPE,
    "SETUP_KEBANGSAAN": SETUP_KEBANGSAAN,
    "SETUP_EDUCATION": SETUP_EDUCATION,
    "SETUP_SMF_DOKTER": SETUP_SMF_DOKTER,
    "SETUP_SPESIALISASI_DOKTER": SETUP_SPESIALISASI_DOKTER,
    "SETUP_STATUS_DOKTER": SETUP_STATUS_DOKTER,
    "JENIS_IDENTITAS": JENIS_IDENTITAS,
    "MARITAL_STATUS": MARITAL_STATUS,
    "SETUP_PROVINSI": SETUP_PROVINSI,
    "SETUP_KOTA": SETUP_KOTA,
    "SETUP_KECAMATAN": SETUP_KECAMATAN,
})