import * as SETUP_GRUP_TARIF from '../SETUP_DATA/SETUP_GRUP_TARIF';
import * as SETUP_KELOMPOK_TARIF from '../SETUP_DATA/SETUP_KELOMPOK_TARIF';
import * as SETUP_TARIF from '../SETUP_DATA/SETUP_TARIF';

export const API_SETUP_DATA = Object.assign({}, {
    "SETUP_GRUP_TARIF": SETUP_GRUP_TARIF,
    "SETUP_KELOMPOK_TARIF": SETUP_KELOMPOK_TARIF,
    "SETUP_TARIF": SETUP_TARIF,
})