import * as SETUP_GRUP_TARIF from '../SETUP_DATA/SETUP_GRUP_TARIF';
import * as SETUP_KELOMPOK_TARIF from '../SETUP_DATA/SETUP_KELOMPOK_TARIF';
import * as SETUP_TARIF from '../SETUP_DATA/SETUP_TARIF';
import * as SETUP_KELAS_PERAWATAN from '../SETUP_DATA/SETUP_KELAS_PERAWATAN';
import * as SETUP_JENIS_RUANGAN from '../SETUP_DATA/SETUP_JENIS_RUANGAN';
import * as SETUP_POLI from '../SETUP_DATA/SETUP_POLI';
import * as SETUP_TARIF_PAKET from '../SETUP_DATA/SETUP_TARIF_PAKET';

export const API_SETUP_DATA = Object.assign({}, {
    "SETUP_GRUP_TARIF": SETUP_GRUP_TARIF,
    "SETUP_KELOMPOK_TARIF": SETUP_KELOMPOK_TARIF,
    "SETUP_TARIF": SETUP_TARIF,
    "SETUP_KELAS_PERAWATAN": SETUP_KELAS_PERAWATAN,
    "SETUP_JENIS_RUANGAN": SETUP_JENIS_RUANGAN,
    "SETUP_POLI": SETUP_POLI,
    "SETUP_TARIF_PAKET": SETUP_TARIF_PAKET,
})