import * as SETUP_GRUP_TARIF from '../SETUP_DATA/SETUP_GRUP_TARIF';
import * as SETUP_KELOMPOK_TARIF from '../SETUP_DATA/SETUP_KELOMPOK_TARIF';
import * as SETUP_TARIF from '../SETUP_DATA/SETUP_TARIF';
import * as SETUP_KELAS_PERAWATAN from '../SETUP_DATA/SETUP_KELAS_PERAWATAN';
import * as SETUP_JENIS_RUANGAN from '../SETUP_DATA/SETUP_JENIS_RUANGAN';
import * as SETUP_POLI from '../SETUP_DATA/SETUP_POLI';
import * as SETUP_TARIF_PAKET from '../SETUP_DATA/SETUP_TARIF_PAKET';
import * as SETUP_PAYMENT_METHOD from '../SETUP_DATA/SETUP_PAYMENT_METHOD';
import * as SETUP_BANK_PAYMENT from '../SETUP_DATA/SETUP_BANK_PAYMENT';
import * as SETUP_VOUCHER_PAYMENT from '../SETUP_DATA/SETUP_VOUCHER_PAYMENT';
import * as SETUP_EDC_PAYMENT from '../SETUP_DATA/SETUP_EDC_PAYMENT';
import * as SETUP_TIKET_PEMERIKSAAN from '../SETUP_DATA/SETUP_TIKET_PEMERIKSAAN';

export const API_SETUP_DATA = Object.assign({}, {
    "SETUP_GRUP_TARIF": SETUP_GRUP_TARIF,
    "SETUP_KELOMPOK_TARIF": SETUP_KELOMPOK_TARIF,
    "SETUP_TARIF": SETUP_TARIF,
    "SETUP_KELAS_PERAWATAN": SETUP_KELAS_PERAWATAN,
    "SETUP_JENIS_RUANGAN": SETUP_JENIS_RUANGAN,
    "SETUP_POLI": SETUP_POLI,
    "SETUP_TARIF_PAKET": SETUP_TARIF_PAKET,
    "SETUP_PAYMENT_METHOD": SETUP_PAYMENT_METHOD,
    "SETUP_BANK_PAYMENT": SETUP_BANK_PAYMENT,
    "SETUP_VOUCHER_PAYMENT": SETUP_VOUCHER_PAYMENT,
    "SETUP_EDC_PAYMENT": SETUP_EDC_PAYMENT,
    "SETUP_TIKET_PEMERIKSAAN": SETUP_TIKET_PEMERIKSAAN,
})