import * as SETUP_BED_IRNA from './SETUP_BED_IRNA';
import * as DAFTAR_ANTRIAN_PEMESANAN_BED from './DAFTAR_ANTRIAN_PEMESANAN_BED';
import * as ADMISI_PASIEN_RAWAT_INAP from './ADMISI_PASIEN_RAWAT_INAP';

export const IRNA = Object.assign({},
    {
        "SETUP_BED_IRNA": SETUP_BED_IRNA,
        "DAFTAR_ANTRIAN_PEMESANAN_BED": DAFTAR_ANTRIAN_PEMESANAN_BED,
        "ADMISI_PASIEN_RAWAT_INAP": ADMISI_PASIEN_RAWAT_INAP,
    }
)