
import {SETUP_DATA} from './SETUP-DATA'
import {FORMULARIUM} from './FORMULARIUM'
import {RESEP_DOKTER} from './RESEP-DOKTER'
import {TRANSAKSI_OBAT} from './TRANSAKSI-OBAT'
import {RETUR_PENJUALAN} from './RETUR-PENJUALAN-OBAT'
import {RESEP_FORMULARIUM} from './RESEP-FORMULARIUM'

export const PHARMACY = Object.assign({}, 
    {
        "SETUP_DATA":SETUP_DATA,
        "FORMULARIUM":FORMULARIUM,
        "RESEP_DOKTER":RESEP_DOKTER,
        "TRANSAKSI_OBAT":TRANSAKSI_OBAT,
        "RETUR_PENJUALAN":RETUR_PENJUALAN,
        "RESEP_FORMULARIUM":RESEP_FORMULARIUM
    }
)