import * as PENDAFTARAN_PASIEN_BARU from './PENDAFTARAN_PASIEN_BARU';
import * as DAFTAR_PASIEN_IRJA from './DAFTAR_PASIEN_IRJA';
import * as EDIT_PASIEN from './EDIT_PASIEN';
import * as PELAYANAN_RAWAT_JALAN from './PELAYANAN_RAWAT_JALAN';
import * as PEMASUKAN_RAWAT_JALAN from './PEMASUKAN_IRJA';
import * as ANTRIAN_PASIEN_RAWAT_JALAN from './ANTRIAN_PASIEN_RAWAT_JALAN';
import * as TRANSFER_TAGIHAN_IRJA_IRNA from './TRANSFER_TAGIHAN_IRJA_IRNA';

export const IRJA = Object.assign({},
    {
        "PENDAFTARAN_PASIEN_BARU": PENDAFTARAN_PASIEN_BARU,
        "DAFTAR_PASIEN_IRJA": DAFTAR_PASIEN_IRJA,
        "EDIT_PASIEN": EDIT_PASIEN,
        "PELAYANAN_RAWAT_JALAN": PELAYANAN_RAWAT_JALAN,
        "PEMASUKAN_RAWAT_JALAN": PEMASUKAN_RAWAT_JALAN,
        "ANTRIAN_PASIEN_RAWAT_JALAN": ANTRIAN_PASIEN_RAWAT_JALAN,
        "TRANSFER_TAGIHAN_IRJA_IRNA": TRANSFER_TAGIHAN_IRJA_IRNA,
    }
)