import * as PENDAFTARAN_PASIEN_BARU from './PENDAFTARAN_PASIEN_BARU';
import * as DAFTAR_PASIEN_IRJA from './DAFTAR_PASIEN_IRJA';
import * as EDIT_PASIEN from './EDIT_PASIEN';

export const IRJA = Object.assign({},
    {
        "PENDAFTARAN_PASIEN_BARU": PENDAFTARAN_PASIEN_BARU,
        "DAFTAR_PASIEN_IRJA": DAFTAR_PASIEN_IRJA,
        "EDIT_PASIEN": EDIT_PASIEN,
    }
)