version: "3.8"

services:
  frontend_his:
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    image: his/frontend_his:${BUILD_DATE}.${BUILD_VERSION}
    container_name: frontend_his
    ports:
      - "80:80"
    networks:
      - api-network

networks:
  api-network:
    external: true
