
import * as SETUP_SATUAN from './SETUP_SATUAN';
import * as SETUP_PABRIK from './SETUP_PABRIK'
import * as SETUP_COA  from "./SETUP_COA";
import * as SETUP_GROUP_COA  from "./SETUP_GROUP_COA";
import * as SETUP_GROUP_ITEM  from "./SETUP_GROUP_ITEM";
import * as SETUP_ITEM  from "./SETUP_ITEM";
import * as SETUP_KONVERSI_SATUAN  from "./SETUP_KONVERSI_SATUAN";
import * as SETUP_PERENCANAAN_KATEGORI  from "./SETUP_PERENCANAAN_KATEGORI";
import * as SETUP_STOCKROOM  from "./SETUP_STOCKROOM";
import * as SETUP_STOCKROOM_ITEM  from "./SETUP_STOCKROOM_ITEM";
import * as SETUP_SUPPLIER  from "./SETUP_SUPPLIER";
import * as SETUP_SUPPLIER_REKENING  from "./SETUP_SUPPLIER_REKENING";
import * as SETUP_TEMPERATUR_ITEM  from "./SETUP_TEMPERATUR_ITEM";
import * as SETUP_TIPE_ITEM  from "./SETUP_TIPE_ITEM";
import * as SETUP_TIPE_SUPPLIER  from "./SETUP_TIPE_SUPPLIER";
import * as SETUP_TIPE_STOCKROOM from './SETUP_TIPE_STOCKROOM';
import * as SETUP_JENIS_PENERIMAAN from './SETUP_JENIS_PENERIMAAN';
import * as SETUP_PAYMENT_TERM from './SETUP_PAYMENT_TERM'
import * as SETUP_SHIPPING_METHOD from './SETUP_SHIPPING_METHOD';
import * as SETUP_MEKANISME_RETUR from './SETUP_MEKANISME_RETUR';

export const SETUP_DATA = Object.assign({},{
        "SETUP_SHIPPING_METHOD":SETUP_SHIPPING_METHOD,
        "SETUP_PAYMENT_TERM":SETUP_PAYMENT_TERM,
        "SETUP_JENIS_PENERIMAAN":SETUP_JENIS_PENERIMAAN,
        "SETUP_PABRIK":SETUP_PABRIK,
        "SETUP_SATUAN":SETUP_SATUAN,
        "SETUP_COA":SETUP_COA,
        "SETUP_GROUP_COA":SETUP_GROUP_COA,
        "SETUP_GROUP_ITEM":SETUP_GROUP_ITEM,
        "SETUP_ITEM":SETUP_ITEM,
        "SETUP_KONVERSI_SATUAN":SETUP_KONVERSI_SATUAN,
        "SETUP_PERENCANAAN_KATEGORI":SETUP_PERENCANAAN_KATEGORI,
        "SETUP_STOCKROOM":SETUP_STOCKROOM,
        "SETUP_STOCKROOM_ITEM":SETUP_STOCKROOM_ITEM,
        "SETUP_SUPPLIER":SETUP_SUPPLIER,
        "SETUP_SUPPLIER_REKENING":SETUP_SUPPLIER_REKENING,
        "SETUP_TEMPERATUR_ITEM":SETUP_TEMPERATUR_ITEM,
        "SETUP_TIPE_ITEM":SETUP_TIPE_ITEM,
        "SETUP_TIPE_SUPPLIER":SETUP_TIPE_SUPPLIER,
        "SETUP_TIPE_STOCKROOM":SETUP_TIPE_STOCKROOM,
        "SETUP_MEKANISME_RETUR":SETUP_MEKANISME_RETUR
    }
)