import * as ADMISI_PASIEN_RAWAT_DARURAT from './ADMISI_PASIEN_RAWAT_DARURAT';
import * as UPDATE_PASIEN_TANPA_IDENTITAS from './UPDATE_PASIEN_TANPA_IDENTITAS';
import * as PEMASUKAN_RAWAT_DARURAT from './PEMASUKAN_RAWAT_DARURAT';
import * as TRANSFER_TAGIHAN_IRDA_IRNA from './TRANSFER_TAGIHAN_IRDA_IRNA';

export const IRDA = Object.assign({},
    {
        "ADMISI_PASIEN_RAWAT_DARURAT": ADMISI_PASIEN_RAWAT_DARURAT,
        "UPDATE_PASIEN_TANPA_IDENTITAS": UPDATE_PASIEN_TANPA_IDENTITAS,
        "PEMASUKAN_RAWAT_DARURAT": PEMASUKAN_RAWAT_DARURAT,
        "TRANSFER_TAGIHAN_IRDA_IRNA": TRANSFER_TAGIHAN_IRDA_IRNA
    }
)