import * as ADMISI_PASIEN_RAWAT_DARURAT from './ADMISI_PASIEN_RAWAT_DARURAT';
import * as UPDATE_PASIEN_TANPA_IDENTITAS from './UPDATE_PASIEN_TANPA_IDENTITAS';
import * as PEMASUKAN_RAWAT_DARURAT from './PEMASUKAN_RAWAT_DARURAT';

export const IRDA = Object.assign({},
    {
        "ADMISI_PASIEN_RAWAT_DARURAT": ADMISI_PASIEN_RAWAT_DARURAT,
        "UPDATE_PASIEN_TANPA_IDENTITAS": UPDATE_PASIEN_TANPA_IDENTITAS,
        "PEMASUKAN_RAWAT_DARURAT": PEMASUKAN_RAWAT_DARURAT,
    }
)