
import * as SETTING_STOK_OPNAME from './SETTING_STOK_OPNAME'
import * as AUDIT_STOK_OPNAME from './AUDIT_STOK_OPNAME'
import * as AUDIT_STOK_OPNAME_TANPA_SETTING from './AUDIT_STOK_OPNAME_TANPA_SETTING'

export const STOK_OPNAME = Object.assign({}, 
    {
        "SETTING_STOK_OPNAME":SETTING_STOK_OPNAME,
        "AUDIT_STOK_OPNAME":AUDIT_STOK_OPNAME,
        "AUDIT_STOK_OPNAME_TANPA_SETTING":AUDIT_STOK_OPNAME_TANPA_SETTING
    }
)