version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t dockerhiscis/frontend-his:$CIRCLE_SHA1 .

      - run:
          name: Push Docker Image
          command: |
            docker push dockerhiscis/frontend-his:$CIRCLE_SHA1
            docker tag dockerhiscis/frontend-his:$CIRCLE_SHA1 dockerhiscis/frontend-his:latest
            docker push dockerhiscis/frontend-his:latest

      - add_ssh_keys:
          fingerprints:
            # - "82:92:b4:65:61:1d:5f:67:0b:63:63:6a:d1:09:a1:5e"
            # ssh -o StrictHostKeyChecking=no his-admin@134.209.102.123 "cd /home/his-admin/frontend-his/ && ./deploy.sh"
            - "ff:78:f1:c9:e9:45:cc:c8:ca:45:3b:3b:fb:74:5a:df"

      - run:
          name: Deploy app to docker swarm via ssh
          command: |
            ssh -o StrictHostKeyChecking=no root@174.138.22.139 "cd /home/frontend-his-circle/ && docker-compose down && docker pull dockerhiscis/frontend-his:latest && docker-compose up -d"
