version: 2
jobs:
  build:
    machine: true
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Build dockerfile
          command: |
            docker build -t dockerhiscis/frontend-his .

      - run:
          name: Push Docker Image
          command: |
            docker tag dockerhiscis/frontend-his dockerhiscis/frontend-his:$CIRCLE_SHA1
            docker push dockerhiscis/frontend-his:$CIRCLE_SHA1
            docker tag dockerhiscis/frontend-his dockerhiscis/frontend-his:latest
            docker push dockerhiscis/frontend-his:latest

      - add_ssh_keys:
          fingerprints:
            - "82:92:b4:65:61:1d:5f:67:0b:63:63:6a:d1:09:a1:5e"

      - run:
          name: Deploy app to docker swarm via ssh
          command: |
            ssh -o StrictHostKeyChecking=no his-admin@134.209.102.123 "cd /home/frontend-his/ && ./deploy.sh"
