version: 2
jobs:
  build:
    machine: true
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Build dockerfile
          command: |
            docker build -t dockerhiscis/frontend-his .

      - run:
          name: Push Docker Image
          command: |
            docker tag dockerhiscis/node-testing dockerhiscis/frontend-his:$CIRCLE_SHA1
            docker push dockerhiscis/frontend-his:$CIRCLE_SHA1
            docker tag dockerhiscis/frontend-his dockerhiscis/frontend-his:latest
            docker push dockerhiscis/frontend-his:latest
