
import {PENERIMAAN} from '../MM_TANPA_ED/PENERIMAAN_TANPA_ED'
import {MUTASI_TANPA_ED} from '../MM_TANPA_ED/MUTASI_TANPA_ED'
import {RETUR_TANPA_ED} from '../MM_TANPA_ED/RETUR_TANPA_ED'
import {PEMAKAIAN_INTERNAL_TANPA_ED} from '../MM_TANPA_ED/PEMAKAIAN_INTERNAL_TANPA_ED'
import {REPACK} from './REPACKING'
import {ASSEM} from './ASSEMBLY'
import {PEMUSNAHAN} from './PEMUSNAHAN'
import {STOK_OPNAME} from './STOK_OPNAME'

export const MM_TANPA_ED = Object.assign({}, 
    {
        "PENERIMAAN_TANPA_ED":PENERIMAAN,
        "MUTASI_TANPA_ED":MUTASI_TANPA_ED,
        "RETUR_TANPA_ED":RETUR_TANPA_ED,
        "PEMAKAIAN_INTERNAL_TANPA_ED":PEMAKAIAN_INTERNAL_TANPA_ED,
        "REPACK":REPACK,
        "ASSEM":ASSEM,
        "PEMUSNAHAN":PEMUSNAHAN,
        "STOK_OPNAME":STOK_OPNAME
    }
)