
import * as RETUR_PENJUALAN_OBAT_IRJA from './RETUR_PENJUALAN_OBAT_IRJA';
import * as RETUR_PENJUALAN_OBAT_IRDA from './RETUR_PENJUALAN_OBAT_IRDA';
import * as RETUR_PENJUALAN_OBAT_IRNA from './RETUR_PENJUALAN_OBAT_IRNA';

export const TRANSAKSI_OBAT = Object.assign({},
    {
    "RETUR_PENJUALAN_OBAT_IRJA":RETUR_PENJUALAN_OBAT_IRJA,
    "RETUR_PENJUALAN_OBAT_IRDA":RETUR_PENJUALAN_OBAT_IRDA,
    "RETUR_PENJUALAN_OBAT_IRNA":RETUR_PENJUALAN_OBAT_IRNA
    }
)