import * as SETTING_TARIF_BERLAKU from '../SETTING_HARGA_TARIF/SETTING_TARIF_BERLAKU';
import * as SETTING_TARIF_PER_POLI from '../SETTING_HARGA_TARIF/SETTING_TARIF_PER_POLI';

export const API_SETTING_HARGA_TARIF = Object.assign({}, {
    "SETTING_TARIF_BERLAKU": SETTING_TARIF_BERLAKU,
    "SETTING_TARIF_PER_POLI": SETTING_TARIF_PER_POLI,
})