
import * as TRANSPEMAKAIANINTERNAL from './TRANSPEMAKAIANINTERNAL'
import * as TRANSRETURPEMAKAIANINTERNAL from './TRANSRETURPEMAKAIANINTERNAL'
export const PEMAKAIAN_INTERNAL = Object.assign({}, 
    {"TRANSPEMAKAIANINTERNAL":TRANSPEMAKAIANINTERNAL},
    {"TRANSRETURPEMAKAIANINTERNAL":TRANSRETURPEMAKAIANINTERNAL}
)