
import * as RESEP_FORMULARIUM_IRJA from './RESEP-FORMULARIUM-IRJA';
import * as RESEP_FORMULARIUM_IRNA from './RESEP-FORMILARIUM-IRNA';
import * as RESEP_FORMULARIUM_IRDA from './RESEP-FORMILARIUM-IRDA';
export const RESEP_FORMULARIUM = Object.assign({},{
        "RESEP_FORMULARIUM_IRJA": RESEP_FORMULARIUM_IRJA,
        "RESEP_FORMULARIUM_IRNA": RESEP_FORMULARIUM_IRNA,
        "RESEP_FORMULARIUM_IRDA": RESEP_FORMULARIUM_IRDA
    }
)