
import * as TRANSPEMAKAIANINTERNAL_TANPA_ED from './TRANSPEMAKAIANINTERNAL_TANPA_ED'
import * as TRANSRETURPEMAKAIANINTERNAL_TANPA_ED from './TRANSRETURPEMAKAIANINTERNAL_TANPA_ED'
export const PEMAKAIAN_INTERNAL_TANPA_ED = Object.assign({}, 
    {"TRANSPEMAKAIANINTERNAL_TANPA_ED":TRANSPEMAKAIANINTERNAL_TANPA_ED},
    {"TRANSRETURPEMAKAIANINTERNAL_TANPA_ED":TRANSRETURPEMAKAIANINTERNAL_TANPA_ED}
)