
import * as SETTING_STOK_OPNAME_TANPA_ED from './SETTING_STOK_OPNAME_TANPA_ED'
import * as AUDIT_STOK_OPNAME_TANPA_ED from './AUDIT_STOK_OPNAME_TANPA_ED'
import * as AUDIT_STOK_OPNAME_TANPA_SETTING_TANPA_ED from './AUDIT_STOK_OPNAME_TANPA_SETTING_TANPA_ED'

export const STOK_OPNAME_TANPA_ED = Object.assign({}, 
    {
        "SETTING_STOK_OPNAME_TANPA_ED":SETTING_STOK_OPNAME_TANPA_ED,
        "AUDIT_STOK_OPNAME_TANPA_ED":AUDIT_STOK_OPNAME_TANPA_ED,
        "AUDIT_STOK_OPNAME_TANPA_SETTING_TANPA_ED":AUDIT_STOK_OPNAME_TANPA_SETTING_TANPA_ED
    }
)