
import * as PENGAJUAN_MUTASI from './PENGAJUAN_MUTASI'
import * as PERSETUJUAN_MUTASI from './PERSETUJUAN_MUTASI'
export const MUTASI = Object.assign({}, 
    {"PENGAJUAN_MUTASI":PENGAJUAN_MUTASI},
    {"PERSETUJUAN_MUTASI":PERSETUJUAN_MUTASI}
)