
import * as PENGAJUAN_MUTASI_TANPA_ED from './PENGAJUAN_MUTASI_TANPA_ED'
import * as PERSETUJUAN_MUTASI_TANPA_ED from './PERSETUJUAN_MUTASI_TANPA_ED'
export const MUTASI_TANPA_ED = Object.assign({}, 
    {"PENGAJUAN_MUTASI_TANPA_ED":PENGAJUAN_MUTASI_TANPA_ED},
    {"PERSETUJUAN_MUTASI_TANPA_ED":PERSETUJUAN_MUTASI_TANPA_ED}
)