
import * as SETUP_GENERIK from './SETUP_GENERIK';
import * as SETUP_JENIS_FORMULARIUM from './SETUP_JENIS_FORMULARIUM';
import * as SETUP_PERESEPAN_MAKSIMAL from './SETUP_PERESEPAN_MAKSIMAL';
import * as SETUP_RESTRIKSI_OBAT from './SETUP_RESTRIKSI_OBAT';
import * as SETUP_SEDIAAN_OBAT from './SETUP_SEDIAAN_OBAT';
import * as SETUP_TERAPI from './SETUP_TERAPI';

export const FORMULARIUM = Object.assign({},
    {"SETUP_GENERIK":SETUP_GENERIK},
    {"SETUP_JENIS_FORMULARIUM":SETUP_JENIS_FORMULARIUM},
    {"SETUP_PERESEPAN_MAKSIMAL":SETUP_PERESEPAN_MAKSIMAL},
    {"SETUP_RESTRIKSI_OBAT":SETUP_RESTRIKSI_OBAT},
    {"SETUP_SEDIAAN_OBAT":SETUP_SEDIAAN_OBAT},
    {"SETUP_TERAPI":SETUP_TERAPI}
)