
import * as TRANSAKSI_OBAT_IRJA from './TRANSAKSI-OBAT-IRJA';
import * as TRANSAKSI_OBAT_IRNA from './TRANSAKSI-OBAT-IRNA';
export const TRANSAKSI_OBAT = Object.assign({},
    {"TRANSAKSI_OBAT_IRJA":TRANSAKSI_OBAT_IRJA},
    {"TRANSAKSI_OBAT_IRNA":TRANSAKSI_OBAT_IRNA}
)