
import * as TRANSAKSI_OBAT_IRJA from './TRANSAKSI-OBAT-IRJA';
import * as TRANSAKSI_OBAT_IRNA from './TRANSAKSI-OBAT-IRNA';
import * as TRANSAKSI_OBAT_IRDA from './TRANSAKSI-OBAT-IRDA';
export const TRANSAKSI_OBAT = Object.assign({},
    {"TRANSAKSI_OBAT_IRJA":TRANSAKSI_OBAT_IRJA,
    "TRANSAKSI_OBAT_IRDA" :TRANSAKSI_OBAT_IRDA,
    "TRANSAKSI_OBAT_IRNA":TRANSAKSI_OBAT_IRNA}
)