
import * as RESEP_DOKTER_IRJA from './RESEP_DOKTER_IRJA';
import * as RESEP_DOKTER_IRNA from './RESEP_DOKTER_IRNA';
export const RESEP_DOKTER = Object.assign({},
    {"RESEP_DOKTER_IRJA":RESEP_DOKTER_IRJA},
    {"RESEP_DOKTER_IRNA":RESEP_DOKTER_IRNA}
)