
import * as SETUP_OUTLET from './SETUP_OUTLET';
import * as SETUP_TIPE_OUTLET from './SETUP_TIPE_OUTLET';
import * as SETUP_GRUP_OBAT from './SETUP_GRUP_OBAT';
import * as SETUP_CARA_PAKAI_OBAT from './SETUP_CARA_PAKAI_OBAT';
import * as SETUP_RUTE_PEMBERIAN_OBAT from './SETUP_RUTE_PEMBERIAN_OBAT';
import * as SETUP_LABEL_PEMAKAIAN_OBAT from './SETUP_LABEL_PEMAKAIAN_OBAT';
import * as SETUP_TAMBAHAN_ATURAN_PAKAI from './SETUP_TAMBAHAN_ATURAN_PAKAI';
import * as SETUP_METODE_RACIKAN from './SETUP_METODE_RACIKAN';
import * as SETUP_SATUAN_ATURAN_PAKAI from './SETUP_SATUAN_ATURAN_PAKAI';
import * as SETUP_INTERVAL_ATURAN_PAKAI from './SETUP_INTERVAL_ATURAN_PAKAI';

export const SETUP_DATA = Object.assign({},
    {"SETUP_OUTLET":SETUP_OUTLET},
    {"SETUP_TIPE_OUTLET":SETUP_TIPE_OUTLET},
    {"SETUP_GRUP_OBAT":SETUP_GRUP_OBAT},
    {"SETUP_CARA_PAKAI_OBAT":SETUP_CARA_PAKAI_OBAT},
    {"SETUP_RUTE_PEMBERIAN_OBAT":SETUP_RUTE_PEMBERIAN_OBAT},
    {"SETUP_LABEL_PEMAKAIAN_OBAT":SETUP_LABEL_PEMAKAIAN_OBAT},
    {"SETUP_TAMBAHAN_ATURAN_PAKAI":SETUP_TAMBAHAN_ATURAN_PAKAI},
    {"SETUP_METODE_RACIKAN":SETUP_METODE_RACIKAN},
    {"SETUP_SATUAN_ATURAN_PAKAI":SETUP_SATUAN_ATURAN_PAKAI},
    {"SETUP_INTERVAL_ATURAN_PAKAI":SETUP_INTERVAL_ATURAN_PAKAI}
)