
import * as TRANSKONTRAKSPJB from './TRANSKONTRAKSPJB'
import * as TRANSPEMESANAN from './TRANSPEMESANAN'
import * as TRANSPENERIMAAN from './TRANSPENERIMAAN'
export const PENERIMAAN = Object.assign({}, 
    {"TRANSKONTRAKSPJB":TRANSKONTRAKSPJB},
    {"TRANSPEMESANAN":TRANSPEMESANAN},
    {"TRANSPENERIMAAN":TRANSPENERIMAAN}
)