
import * as TRANSKONTRAKSPJB from './TRANSKONTRAKSPJB'
import * as TRANSPEMESANAN from './TRANSPEMESANAN'
import * as TRANSPENERIMAAN from './TRANSPENERIMAAN'
import * as SETHARGA_ORDER from './SETHARGA_ORDER'
export const PENERIMAAN = Object.assign({}, 
    {"TRANSKONTRAKSPJB":TRANSKONTRAKSPJB},
    {"TRANSPEMESANAN":TRANSPEMESANAN},
    {"TRANSPENERIMAAN":TRANSPENERIMAAN},
    {"SETHARGA_ORDER":SETHARGA_ORDER}
)