
import * as TRANSKONTRAKSPJB from './TRANSKONTRAKSPJB'
import * as TRANSPEMESANAN from './TRANSPEMESANAN'
export const PENERIMAAN = Object.assign({}, 
    {"TRANSKONTRAKSPJB":TRANSKONTRAKSPJB},
    {"TRANSPEMESANAN":TRANSPEMESANAN}
)